name: C/C++ CI

on:
  push:
    branches: [ branch-3.7.15 ]
  pull_request:
    branches: [ branch-3.7.15 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: mkdir
      run: mkdir sqlite2
    - name: configure 
      run: ./configure --prefix=/home/runner/work/sqlite/sqlite/sqlite2 --host=arm
    - name: make
      run: make
    - name: make test
      run: make test
    - name: zip
      run: zip sq.zip ./*
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
       name: sqlite3
       path: ./sq.zip

 
