name: C/C++ CI

on:
  push:
    branches: [ branch-3.7.15 ]
  pull_request:
    branches: [ branch-3.7.15 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: mkdir
      run: mkdir sqlite2
    - name: wget1
      run: wget -O config.guess 'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD'
    - name: wget2
      run: wget -O config.sub 'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD'
    - name: configure 
      run: ./configure --prefix=/home/runner/work/sqlite/sqlite/sqlite2 --host=aarch64
    - name: make
      run: make
    - name: zip
      run: zip sq.zip ./*
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
       name: sqlite3
       path: ./sq.zip

 
