name: C/C++ CI

on:
  push:
    branches: [ branch-3.7.15 ]
  pull_request:
    branches: [ branch-3.7.15 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
